"use client";
import { FormEvent, useState } from "react";
import styles from "./machine-check.module.css";

type Result={status:string;summary:string;conditions:{subject:string;status:string;detail:string;evidence:string[]}[]};
export function MachineCheckPanel({publicId}:{publicId:string}){const[os,setOs]=useState("Windows");const[architecture,setArchitecture]=useState("x86_64");const[python,setPython]=useState("");const[node,setNode]=useState("");const[java,setJava]=useState("");const[docker,setDocker]=useState("");const[result,setResult]=useState<Result|null>(null);const[error,setError]=useState("");const[loading,setLoading]=useState(false);
  async function check(event:FormEvent){event.preventDefault();setLoading(true);setError("");try{const response=await fetch(`${process.env.NEXT_PUBLIC_API_URL??"http://localhost:8000"}/api/v1/analyses/${encodeURIComponent(publicId)}/compatibility`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({operating_system:os,cpu_architecture:architecture,python_version:python||null,node_version:node||null,java_version:java||null,docker_available:docker===""?null:docker==="yes"})});if(!response.ok)throw new Error("Compatibility could not be checked. Try again.");setResult(await response.json() as Result);}catch(reason){setResult(null);setError(reason instanceof Error?reason.message:"Compatibility could not be checked.");}finally{setLoading(false);}}
  return <section className={styles.panel} aria-labelledby="machine-title"><header><p className="eyebrow">Machine compatibility</p><h2 id="machine-title">Will this run on your machine?</h2><p>Enter only what you know. RepoLive compares your answers with explicit repository requirements and leaves missing information as unknown.</p></header><form onSubmit={check}><div className={styles.fields}><Field label="Operating system"><select value={os} onChange={event=>setOs(event.target.value)}><option>Windows</option><option>Linux</option><option>macOS</option></select></Field><Field label="CPU architecture"><select value={architecture} onChange={event=>setArchitecture(event.target.value)}><option value="x86_64">64-bit Intel/AMD</option><option value="arm64">ARM64</option><option value="x86">32-bit Intel/AMD</option></select></Field><Field label="Python version" hint="Example: 3.12"><input inputMode="decimal" placeholder="3.12" value={python} onChange={event=>setPython(event.target.value)}/></Field><Field label="Node version" hint="Example: 22"><input inputMode="decimal" placeholder="22" value={node} onChange={event=>setNode(event.target.value)}/></Field><Field label="Java version" hint="Example: 21"><input inputMode="numeric" placeholder="21" value={java} onChange={event=>setJava(event.target.value)}/></Field><Field label="Docker"><select value={docker} onChange={event=>setDocker(event.target.value)}><option value="">I don’t know</option><option value="yes">Available</option><option value="no">Not available</option></select></Field></div><button className="primaryButton" disabled={loading}>{loading?"Checking…":"Check my machine"}</button></form>{error&&<p className="notice error" role="alert">{error}</p>}{result&&<div className={styles.result} role="status"><span className={styles.status}>{result.status.replace("_"," ")}</span><h3>Compatibility result</h3><p>{result.summary}</p>{result.conditions.length?<ul>{result.conditions.map(item=><li key={item.subject}><strong>{item.subject}: {item.status.replace("_"," ")}</strong><span>{item.detail}</span>{item.evidence.length>0&&<small>Evidence: {item.evidence.join(", ")}</small>}</li>)}</ul>:<div className="emptyState">The repository does not declare enough requirements for a confident comparison.</div>}</div>}</section>;
}
function Field({label,hint,children}:{label:string;hint?:string;children:React.ReactNode}){return <label><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>}
