import Link from "next/link";
import type { Report } from "../../analyze/page";
import styles from "./report.module.css";

export function ReportView({ report }: { report: Report & { cache_status?: string; snapshot: Report["snapshot"] & { ingestion_warnings?: string[] } } }) {
  const { snapshot, analysis } = report;
  const warnings = snapshot.ingestion_warnings ?? [];
  return <section className={styles.report} aria-labelledby="report-title">
    <header className={styles.reportHeader}><div><p className="eyebrow">Analysis complete</p><h1 id="report-title">{snapshot.repository.owner} / {snapshot.repository.name}</h1><p>{analysis.purpose_summary}</p></div><div className={styles.actions}>{report.cache_status==="cached"&&<span className={styles.cacheBadge}>Cached report reused</span>}{report.public_id&&<Link href={`/analysis/${report.public_id}`}>Share report</Link>}<a href={snapshot.repository.canonical_url} target="_blank" rel="noreferrer">GitHub <span aria-hidden="true">↗</span></a></div></header>
    {warnings.length>0&&<aside className="notice warning" aria-label="Partial analysis warning"><strong>Partial analysis</strong><p>Some repository evidence could not be read, but the available findings are still shown.</p><ul>{warnings.map(item=><li key={item}>{item}</li>)}</ul></aside>}
    <nav className={styles.jumpNav} aria-label="Report sections"><a href="#overview">Overview</a><a href="#health">Health</a><a href="#stack">Stack</a><a href="#setup">Setup</a><a href="#evidence">Evidence</a></nav>
    <ReportSection id="overview" title="Overview" copy="The essential facts at a glance."><div className={styles.metrics}>{[["Files examined",snapshot.files.length],["Stars",snapshot.metadata.stars],["Forks",snapshot.metadata.forks],["Open issues",snapshot.metadata.open_issues]].map(([label,value])=><div key={label}><strong>{Number(value).toLocaleString()}</strong><span>{label}</span></div>)}</div><div className={styles.grid}><Card title="Project profile" help="The broad kind of software RepoLive detected."><Tags values={analysis.project_types}/></Card><Card title="What this means"><p className={styles.plainText}>RepoLive uses repository files as evidence. A missing signal means “not found,” not necessarily “bad” or “unsafe.”</p></Card></div></ReportSection>
    <ReportSection id="health" title="Repository health" copy="Explainable project-readiness signals, not a security certification."><div className={styles.scoreGrid}>{analysis.scores.map(score=><article className={styles.score} key={score.name}><div><h3>{score.name}</h3><strong>{score.value}<small>/100</small></strong></div><progress max="100" value={score.value}>{score.value}%</progress><details><summary>Why this score?</summary><EvidenceList values={score.factors.map(item=>({label:item.label,evidence:item.evidence}))}/></details></article>)}</div><div className={styles.grid}><Card title="Strengths"><EvidenceList values={analysis.strengths}/></Card><Card title="Risks and missing essentials"><EvidenceList values={[...analysis.risks,...analysis.missing_essentials]}/></Card></div></ReportSection>
    <ReportSection id="stack" title="Languages, frameworks, and requirements" copy="What the project uses and what you may need installed."><div className={styles.grid}><Card title="Languages" help="Percentages use known source-file bytes.">{analysis.languages.length?analysis.languages.map(item=><div className={styles.language} key={item.name}><span>{item.name}</span><strong>{item.share_percent}%</strong><i style={{width:`${item.share_percent}%`}}/></div>):<Empty text="No programming language could be confirmed."/>}</Card><Card title="Frameworks and tools" help="Recognized libraries, package managers, and build tools."><EvidenceList values={analysis.technologies.map(item=>({label:item.name,evidence:item.evidence}))}/></Card><Card title="Runtime requirements" help="Software versions explicitly requested by the repository."><EvidenceList values={analysis.runtimes.map(item=>({label:`${item.runtime}: ${item.version_constraint??"version not specified"}`,evidence:item.evidence}))}/></Card><Card title="Prerequisites"><EvidenceList values={analysis.prerequisites.map(item=>({label:`${item.name}${item.version_constraint?` ${item.version_constraint}`:""}`,evidence:item.evidence}))}/></Card></div><Disclosure title={`Dependencies (${analysis.dependencies.length})`} description="Expand for package-level technical detail."><div className={styles.itemGrid}>{analysis.dependencies.slice(0,100).map(item=><div key={`${item.ecosystem}-${item.name}`}><strong>{item.name}</strong><span>{item.version_constraint??"Version not specified"}</span><small>{item.ecosystem} · {item.source_path}</small></div>)}</div>{analysis.dependencies.length===0&&<Empty text="No supported dependency manifest was found."/>}</Disclosure></ReportSection>
    <ReportSection id="setup" title="Setup guidance" copy="Review all instructions before using them on your computer."><aside className="notice warning"><strong>Commands are display-only</strong><p>Repository-provided commands are untrusted text. RepoLive never runs them. Review each command before copying it into a terminal.</p></aside><div className={styles.steps}>{analysis.setup_steps.map((item,index)=><article key={`${item.title}-${item.source_path}`}><span>{index+1}</span><div><h3>{item.title}</h3><small>{item.origin==="repository"?"Repository-provided instruction — review before running":"RepoLive-generated guidance"} · {item.source_path}</small>{item.command?<code>{item.command}</code>:<p>No command was declared.</p>}</div></article>)}</div>{analysis.setup_steps.length===0&&<Empty text="No supported setup instructions were detected. Read the repository documentation before installing anything."/>}<Card title="Compatibility clues"><EvidenceList values={analysis.compatibility.map(item=>({label:`${item.subject}: ${item.detail}`,evidence:item.evidence}))}/></Card></ReportSection>
    <ReportSection id="evidence" title="Important files and unknowns" copy="See where findings came from and what RepoLive could not confirm."><div className={styles.grid}><Card title="Important files"><div className={styles.fileList}>{analysis.important_files.map(item=><div key={item.path}><code>{item.path}</code><span>{item.role}</span></div>)}</div>{analysis.important_files.length===0&&<Empty text="No important files were identified."/>}</Card><Card title="Unknowns" help="Unknown does not mean unsafe; it means evidence was unavailable."><EvidenceList values={analysis.unknowns}/></Card></div></ReportSection>
  </section>;
}

function ReportSection({id,title,copy,children}:{id:string;title:string;copy:string;children:React.ReactNode}){return <section className={styles.section} id={id}><header><h2>{title}</h2><p>{copy}</p></header>{children}</section>}
function Card({title,help,children}:{title:string;help?:string;children:React.ReactNode}){return <article className={styles.card}><h3>{title}</h3>{help&&<p className={styles.help}>{help}</p>}{children}</article>}
function Disclosure({title,description,children}:{title:string;description:string;children:React.ReactNode}){return <details className={styles.disclosure}><summary><span><strong>{title}</strong><small>{description}</small></span></summary><div>{children}</div></details>}
function Tags({values}:{values:string[]}){return values.length?<div className={styles.tags}>{values.map(value=><span key={value}>{value}</span>)}</div>:<Empty text="No project type was confirmed."/>}
function EvidenceList({values}:{values:{label:string;evidence:string[]}[]}){return values.length?<ul className={styles.evidenceList}>{values.map(item=><li key={`${item.label}-${item.evidence.join()}`}><span>{item.label}</span>{item.evidence.length>0&&<small>Evidence: {item.evidence.join(", ")}</small>}</li>)}</ul>:<Empty text="No supporting evidence was detected."/>}
function Empty({text}:{text:string}){return <p className={styles.empty}>{text}</p>}
