"use client";

import { FormEvent, useState } from "react";
import { SiteHeader } from "../components/site-header";
import styles from "./tools.module.css";

const apiUrl = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000";
type Diagnosis = { label: string; confidence: string; evidence: string[]; safe_next_checks: string[]; unknowns: string[]; disclaimer: string };
type Comparison = { left_repository: string; right_repository: string; dimensions: { name: string; left: string; right: string; explanation: string }[]; shared_dependencies: string[]; summary: string[]; unknowns: string[] };
type Discovery = { cost: string; items: { full_name: string; url: string; description: string | null; primary_language: string | null; stars: number; score: number; ranking_reasons: string[] }[] };

export default function ToolsPage() {
  const [analysisId, setAnalysisId] = useState(""); const [errorText, setErrorText] = useState(""); const [diagnosis, setDiagnosis] = useState<Diagnosis|null>(null);
  const [leftId, setLeftId] = useState(""); const [rightId, setRightId] = useState(""); const [comparison, setComparison] = useState<Comparison|null>(null);
  const [topic, setTopic] = useState(""); const [language, setLanguage] = useState(""); const [projectType, setProjectType] = useState(""); const [discovery, setDiscovery] = useState<Discovery|null>(null);
  const [message, setMessage] = useState("Choose a tool. Repository code and pasted errors are never executed.");
  async function request<T>(url:string, options:RequestInit, apply:(value:T)=>void) { try { const response=await fetch(url,options); const payload=await response.json() as T&{detail?:string}; if(!response.ok) throw new Error(payload.detail??"Request failed."); apply(payload); setMessage("Ready."); } catch(error) { setMessage(error instanceof Error?error.message:"RepoLive is unavailable."); } }
  async function diagnose(event:FormEvent){event.preventDefault();setMessage("Classifying bounded error text...");setDiagnosis(null);await request<Diagnosis>(`${apiUrl}/api/v1/analyses/${encodeURIComponent(analysisId)}/diagnose`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({error_text:errorText})},value=>{setDiagnosis(value);setErrorText("");});}
  async function compare(event:FormEvent){event.preventDefault();setMessage("Comparing cached analysis evidence…");setComparison(null);await request(`${apiUrl}/api/v1/comparisons`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({left_public_id:leftId,right_public_id:rightId})},setComparison);}
  async function discover(event:FormEvent){event.preventDefault();setMessage("Searching GitHub with bounded filters…");setDiscovery(null);const query=new URLSearchParams();if(topic)query.set("topic",topic);if(language)query.set("language",language);if(projectType)query.set("project_type",projectType);await request(`${apiUrl}/api/v1/discover?${query}`,{},setDiscovery);}
  return <div className="pageShell"><SiteHeader context="Product tools"/><main id="main-content" className={styles.tools}><header><p className="eyebrow">DETERMINISTIC PRODUCT TOOLS</p><h1>Diagnose, compare, and discover.</h1><p className="lede">Every result explains its evidence and limitations. RepoLive never executes pasted errors or repository code.</p><p className="notice" role="status" aria-live="polite">{message}</p></header>
    <section className="panel" aria-labelledby="diagnose-title"><h2 id="diagnose-title">Diagnose a pasted error</h2><p className="muted">Analyze the repository first. Remove secrets before submitting error text.</p><form className="stack" onSubmit={diagnose}><label>Analysis ID<input required minLength={8} maxLength={32} value={analysisId} onChange={event=>setAnalysisId(event.target.value)} placeholder="Public analysis ID"/></label><label>Error text<textarea required maxLength={20000} value={errorText} onChange={event=>setErrorText(event.target.value)} placeholder="Paste the error message here"/></label><button className="primaryButton">Diagnose safely</button></form>{diagnosis&&<article className={styles.result}><h3>{diagnosis.label}<span>{diagnosis.confidence} confidence</span></h3><p>{diagnosis.disclaimer}</p><List title="Evidence" items={diagnosis.evidence}/><List title="Safe next checks" items={diagnosis.safe_next_checks}/><List title="Unknowns" items={diagnosis.unknowns}/></article>}</section>
    <section className="panel" aria-labelledby="compare-title"><h2 id="compare-title">Compare two analyzed repositories</h2><p className="muted">Uses existing cached reports and does not execute either repository.</p><form className={styles.inlineForm} onSubmit={compare}><label>First analysis ID<input required minLength={8} maxLength={32} value={leftId} onChange={event=>setLeftId(event.target.value)}/></label><label>Second analysis ID<input required minLength={8} maxLength={32} value={rightId} onChange={event=>setRightId(event.target.value)}/></label><button className="primaryButton">Compare</button></form>{comparison&&<article className={styles.result}><h3>{comparison.left_repository} vs {comparison.right_repository}</h3><div className={styles.tableWrap}><table><thead><tr><th>Dimension</th><th>{comparison.left_repository}</th><th>{comparison.right_repository}</th></tr></thead><tbody>{comparison.dimensions.map(item=><tr key={item.name}><th>{item.name}<small>{item.explanation}</small></th><td>{item.left}</td><td>{item.right}</td></tr>)}</tbody></table></div><List title="Summary" items={comparison.summary}/><List title="Shared dependencies" items={comparison.shared_dependencies}/><List title="Unknowns" items={comparison.unknowns}/></article>}</section>
    <section className="panel" aria-labelledby="discover-title"><h2 id="discover-title">Discover public repositories</h2><p className="muted">One bounded official GitHub search request. Ranking is transparent and stars never dominate.</p><form className={styles.inlineForm} onSubmit={discover}><label>Topic<input maxLength={40} value={topic} onChange={event=>setTopic(event.target.value)} placeholder="accessibility"/></label><label>Language<input maxLength={40} value={language} onChange={event=>setLanguage(event.target.value)} placeholder="Python"/></label><label>Framework or project type<input maxLength={40} value={projectType} onChange={event=>setProjectType(event.target.value)} placeholder="web api"/></label><button className="primaryButton">Search GitHub</button></form>{discovery&&<article className={styles.result}><p>{discovery.cost}</p><div className={styles.cards}>{discovery.items.map(item=><article key={item.full_name}><h3><a href={item.url} target="_blank" rel="noreferrer">{item.full_name}</a><span>{item.score}/100</span></h3><p>{item.description??"No description provided."}</p><small>{item.primary_language??"Language unknown"} · {item.stars.toLocaleString()} stars</small><List title="Why ranked here" items={item.ranking_reasons}/></article>)}</div>{discovery.items.length===0&&<p>No repositories matched these filters.</p>}</article>}</section>
  </main></div>;
}
function List({title,items}:{title:string;items:string[]}){return <section><h4>{title}</h4>{items.length?<ul>{items.map(item=><li key={item}>{item}</li>)}</ul>:<p>None detected.</p>}</section>}
