"use client";
import { FormEvent, useState } from "react";

type Result = { status:string; summary:string; conditions:{subject:string;status:string;detail:string;evidence:string[]}[] };
export default function MachineCheck({publicId}:{publicId:string}) {
  const [os,setOs]=useState("Windows"); const [architecture,setArchitecture]=useState("x86_64");
  const [python,setPython]=useState(""); const [node,setNode]=useState(""); const [java,setJava]=useState(""); const [docker,setDocker]=useState(""); const [result,setResult]=useState<Result|null>(null);
  async function check(event:FormEvent){event.preventDefault();const response=await fetch(`${process.env.NEXT_PUBLIC_API_URL??"http://localhost:8000"}/api/v1/analyses/${encodeURIComponent(publicId)}/compatibility`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({operating_system:os,cpu_architecture:architecture,python_version:python||null,node_version:node||null,java_version:java||null,docker_available:docker===""?null:docker==="yes"})});if(response.ok)setResult(await response.json() as Result);}
  return <section><h2>Will it run on your machine?</h2><p>Enter only what you know. Missing repository requirements remain unknown.</p><form onSubmit={check}><label>Operating system<select value={os} onChange={e=>setOs(e.target.value)}><option>Windows</option><option>Linux</option><option>macOS</option></select></label><label>CPU architecture<select value={architecture} onChange={e=>setArchitecture(e.target.value)}><option value="x86_64">64-bit Intel/AMD</option><option value="arm64">ARM64</option><option value="x86">32-bit Intel/AMD</option></select></label><label>Python version<input placeholder="3.12" value={python} onChange={e=>setPython(e.target.value)}/></label><label>Node version<input placeholder="22" value={node} onChange={e=>setNode(e.target.value)}/></label><label>Java version<input placeholder="21" value={java} onChange={e=>setJava(e.target.value)}/></label><label>Docker<select value={docker} onChange={e=>setDocker(e.target.value)}><option value="">Not specified</option><option value="yes">Available</option><option value="no">Not available</option></select></label><button>Check compatibility</button></form>{result&&<div role="status"><h3>{result.status.replace("_"," ")}</h3><p>{result.summary}</p><ul>{result.conditions.map(item=><li key={item.subject}><b>{item.subject}: {item.status.replace("_"," ")}</b> — {item.detail}{item.evidence.length>0&&<small> Evidence: {item.evidence.join(", ")}</small>}</li>)}</ul></div>}</section>;
}
