"use client";
import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { getAccessToken, getSupabaseClient } from "../../lib/supabase";
import { SiteHeader } from "../components/site-header";
type HistoryItem = { public_id:string; owner:string; repository_name:string; commit_sha:string; saved_at:string; scores:{name:string;value:number}[] };
const apiUrl = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000";
export default function AccountPage() {
  const supabase = getSupabaseClient(); const [email,setEmail]=useState(""); const [password,setPassword]=useState("");
  const [message,setMessage]=useState(supabase?"Sign in to save and revisit analyses.":"Accounts are not configured in this environment.");
  const [history,setHistory]=useState<HistoryItem[]>([]); const [signedIn,setSignedIn]=useState(false);
  async function loadHistory(){const token=await getAccessToken();setSignedIn(Boolean(token));if(!token){setHistory([]);return;}const response=await fetch(`${apiUrl}/api/v1/analyses/me/history`,{headers:{Authorization:`Bearer ${token}`}});if(response.ok)setHistory(await response.json() as HistoryItem[]);}
  useEffect(()=>{if(!supabase)return;const {data}=supabase.auth.onAuthStateChange(()=>{void loadHistory();});return()=>data.subscription.unsubscribe();},[supabase]);
  async function submit(event:FormEvent,mode:"signin"|"signup"){event.preventDefault();if(!supabase)return;const result=mode==="signin"?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password});setMessage(result.error?.message??(mode==="signin"?"Signed in.":"Account created. Check your email if confirmation is enabled."));}
  async function remove(publicId:string){const token=await getAccessToken();if(!token)return;const response=await fetch(`${apiUrl}/api/v1/analyses/me/history/${publicId}`,{method:"DELETE",headers:{Authorization:`Bearer ${token}`}});if(response.ok)await loadHistory();}
  return <div className="pageShell"><SiteHeader context="Your account"/><main id="main-content" className="authLayout"><section className="panel"><p className="eyebrow">Account</p><h1>Your account</h1><p className="muted">Accounts are optional. Sign in to keep a private list of reports you want to revisit.</p><p className="notice" role="status">{message}</p>
    {!signedIn&&<form className="stack"><div className="field"><label htmlFor="account-email">Email address</label><input id="account-email" type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)}/></div><div className="field"><label htmlFor="account-password">Password</label><input id="account-password" type="password" autoComplete="current-password" required minLength={8} value={password} onChange={e=>setPassword(e.target.value)}/><small className="muted">At least 8 characters. RepoLive does not store your password.</small></div><div className="buttonRow"><button className="primaryButton" onClick={e=>void submit(e,"signin")}>Sign in</button><button className="secondaryButton" onClick={e=>void submit(e,"signup")}>Create account</button></div></form>}
    {signedIn&&<><button className="secondaryButton" onClick={()=>void supabase?.auth.signOut()}>Sign out</button><h2>Saved analyses</h2><p className="muted">Reopen a report or remove it from your private history.</p>{history.length===0?<div className="emptyState">No saved analyses yet. Your next signed-in analysis will appear here.</div>:<ul className="historyList">{history.map(item=><li className="historyItem" key={item.public_id}><div><Link href={`/analysis/${item.public_id}`}>{item.owner} / {item.repository_name}</Link><small>Commit {item.commit_sha.slice(0,8)} · Saved {new Date(item.saved_at).toLocaleDateString()}</small><small>{item.scores.map(score=>`${score.name}: ${score.value}`).join(" · ")}</small></div><button className="dangerButton" onClick={()=>void remove(item.public_id)} aria-label={`Remove ${item.owner}/${item.repository_name} from history`}>Remove</button></li>)}</ul>}</>}
  </section></main></div>;
}
